In [2]:
import numpy as np

### 矩阵的定义 和 维度

In [8]:
data1 = np.array([1,2,3,4,5,])
print(data1)

[1 2 3 4 5]


In [9]:
data2 = np.array([[1,2],[3,4]])
print(data2)

[[1 2]
 [3 4]]


In [10]:
#维度
print(data1.shape,data2.shape)

(5,) (2, 2)


In [11]:
#全零矩阵 全1矩阵
print(np.zeros([2,3]),np.ones([2,2]))
#改查
data2[1,0]=5
print(data2)

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]]
[[1 2]
 [5 4]]


### 基本运算

In [14]:
data3 = np.ones([2,3])
print(data3*2)  #对应相乘
print(data3+2)

[[2. 2. 2.]
 [2. 2. 2.]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [18]:
#两个矩阵的 + *
data4 = np.array([[1,2,3],[4,5,6]])
print(data3+data4)
print(data3*data4) #对应元素相乘

[[2. 3. 4.]
 [5. 6. 7.]]
[[1. 2. 3.]
 [4. 5. 6.]]
